###test request for server 
GET http://localhost:4000/

### route to see all wallets 
GET http://localhost:4000/api/wallet

### route to see specific wallet 
GET http://localhost:4000/api/wallet/2

### route creating a new wallet
POST http://localhost:4000/api/wallet
content-type: application/json

{
    "name": "Take out trash",
    "coin": "ethereum",
    "amount": 50,
    "value": 2500,
    "dateOfPurchase": 20220101
}

### route deleting a wallet
DELETE http://localhost:4000/api/wallet/3
